import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'

const IndexPage = () => {
    return (
        <Layout>
            <p>All this site was static generated by Gatsby using DotCMS content API on a Gatsby Source Plugin</p>
            <Link to="/news/">Go to News</Link>
        </Layout>
    )
}

export default IndexPage
